---
# tasks file for ansible-role-reverse-proxy

- name: install base packages
  apt:
    pkg:
      - ufw
      - bmon
      - htop
      - vim
      - nginx

- name: configure firewall rules
  ufw:
      rule: "{{ item.rule }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
  with_items:
      - { rule: 'allow', port: '22', proto: 'tcp' }
      - { rule: 'allow', port: '80', proto: 'tcp' }
      - { rule: 'allow', port: '443', proto: 'tcp' }

- name: set logging
  ufw:
    logging: 'off'

- name: set ufw policy
  ufw:
    state: enabled
    policy: deny

- name: deploy nginx config template
  template:
      src: jitsi.conf.j2
      dest: /etc/nginx/sites-available/jitsi
  notify: restart nginx service

- name: enable vhost
  file:
    src: /etc/nginx/sites-available/jitsi
    dest: /etc/nginx/sites-enabled/jitsi
    state: link
  notify: restart nginx service

- name: enable nginx service
  systemd:
      name: nginx
      enabled: yes
